apiVersion: v1
kind: Secret
metadata:
  name: glenn-portfolio-secret
  labels:
    app: glenn-portfolio
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_KEY: "$AWS_SECRET_KEY"
  AWS_ECR_REPOSITORY: "$AWS_ECR_REPOSITORY"
  APP_CLIENT_ID: "$APP_CLIENT_ID"
  APP_CLIENT_SECRET: "$APP_CLIENT_SECRET"
  KUBE_NAME: "$KUBE_NAME"
